export const ItemList = [
  {
    key: "Azura's Star",
    itemName: "Azura's Star",
    skill: "Enchanting",
    guild: "none",
    link: "https://elderscrolls.fandom.com/wiki/Azura%27s_Star_(Skyrim)",
  },
  {
    key: "Dawnbreaker",
    itemName: "Dawnbreaker",
    skill: "One-Handed",
    guild: "none",
    link: "https://elderscrolls.fandom.com/wiki/Dawnbreaker_(Skyrim)",
  },
  {
    key: "Ebony Blade",
    itemName: "Ebony Blade",
    skill: "Two-Handed",
    guild: "none",
    link: "https://elderscrolls.fandom.com/wiki/Ebony_Blade_(Skyrim)",
  },
  {
    key: "Ebony Mail",
    itemName: "Ebony Mail",
    skill: "Heavy-Armor",
    guild: "none",
    link: "https://elderscrolls.fandom.com/wiki/Ebony_Mail_(Skyrim)",
  },
  {
    key: "Mace of Molag Bal",
    itemName: "Mace of Molag Bal",
    skill: "One-Handed",
    guild: "none",
    link: "https://elderscrolls.fandom.com/wiki/Mace_of_Molag_Bal_(Skyrim)",
  },
  {
    key: "Masque of Clavicus Vile",
    itemName: "Masque of Clavicus Vile",
    skill: "All",
    guild: "none",
    link: "https://elderscrolls.fandom.com/wiki/Masque_of_Clavicus_Vile_(Skyrim)",
  },
  {
    key: "Mehrunes Razor",
    itemName: "Mehrunes Razor",
    skill: "One-Handed",
    guild: "none",
    link: "https://elderscrolls.fandom.com/wiki/Mehrunes%27_Razor_(Skyrim)",
  },
  {
    key: "Oghma Infinium",
    itemName: "Oghma Infinium",
    skill: "All",
    guild: "none",
    link: "https://elderscrolls.fandom.com/wiki/Oghma_Infinium_(Skyrim)",
  },
  {
    key: "Ring of Namira",
    itemName: "Ring of Namira",
    skill: "All",
    guild: "none",
    link: "https://elderscrolls.fandom.com/wiki/Ring_of_Namira_(Skyrim)",
  },
  {
    key: "Sanguine Rose",
    itemName: "Sanguine Rose",
    skill: "Conjuration",
    link: "https://elderscrolls.fandom.com/wiki/Sanguine_Rose_(Skyrim)",
  },
  {
    key: "Ring of Hircine",
    itemName: "Ring of Hircine",
    skill: "All",
    guild: "none",
    link: "https://elderscrolls.fandom.com/wiki/Hircine%27s_Ring_(Skyrim)",
  },
  {
    key: "Skeleton Key",
    itemName: "Skeleton Key",
    skill: "Lockpicking",
    guild: "none",
    link: "https://elderscrolls.fandom.com/wiki/Skeleton_Key_(Skyrim)",
  },
  {
    key: "Skull of Corruption",
    itemName: "Skull of Corruption",
    skill: "Destruction",
    guild: "none",
    link: "https://elderscrolls.fandom.com/wiki/Skull_of_Corruption_(Skyrim)",
  },
  {
    key: "Spellbreaker",
    itemName: "Spellbreaker",
    skill: "Block",
    guild: "none",
    link: "https://elderscrolls.fandom.com/wiki/Spellbreaker_(Skyrim)",
  },
  {
    key: "Volendrung",
    itemName: "Volendrung",
    skill: "Two-Handed",
    guild: "none",
    link: "https://elderscrolls.fandom.com/wiki/Volendrung_(Skyrim)",
  },
  {
    key: "Wabbajack",
    itemName: "Wabbajack",
    skill: "All",
    guild: "none",
    link: "https://elderscrolls.fandom.com/wiki/Wabbajack_(Skyrim)",
  },
];
